### ISSUE TITLE
e-mail Lock Timeout -> retry

### ISSUE THREAD

**Issue by will-moore** [ome/omero-signup#8]
See https://www.openmicroscopy.org/qa2/qa/feedback/29024/

```
Traceback (most recent call last):

File "/opt/omero/web/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/omero/web/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
return self.dispatch(request, *args, **kwargs)

File "/opt/omero/web/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
return handler(request, *args, **kwargs)

File "/opt/omero/web/venv/lib/python2.7/site-packages/omero_signup/views.py", line 124, in post
omeuser = self.create_account(user)

File "/opt/omero/web/venv/lib/python2.7/site-packages/omero_signup/views.py", line 160, in create_account
self._email_user(adminc.c, omeuser)

File "/opt/omero/web/venv/lib/python2.7/site-packages/omero_signup/views.py", line 238, in _email_user
failonerror=True, failontimeout=True)

File "/opt/omero/web/OMERO.web/lib/python/omero/clients.py", line 961, in submit
closehandle=True)

File "/opt/omero/web/OMERO.web/lib/python/omero/clients.py", line 980, in waitOnCmd
callback.loop(loops, ms) # Throw LockTimeout

File "/opt/omero/web/OMERO.web/lib/python/omero/callbacks.py", line 256, in loop
5000L, int(waited))

LockTimeout: exception ::omero::LockTimeout
{
serverStackTrace = None
serverExceptionClass = None
message = Command unfinished after 5.0 seconds
backOff = 5000
seconds = 5
}
```

We could maybe handle this by retrying instead of returning the error to the user.

**Comment by mtbc** [comment]
Does this block upgrading demo to OMERO 5.6? Or does the currently deployed signup also have this issue anyway?

**Comment by joshmoore** [comment]
I'd assume this exists in the original as well.

**Comment by will-moore** [comment]
I have seen this error a few times on demo recently.

**Comment by mtbc** [comment]
Excellent, thank you both.

**Comment by manics** [comment]
Another report on demo `2020-02-14 19:07:05,605`

**Comment by sbesson** [comment]
Similar report on `demo` on `2021-03-17 09:44:48,378`. Matches UoD reported issues. This probably means the user did not get the email with his password
